name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget -N https://chromedriver.storage.googleapis.com/91.0.4472.101/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip -d /usr/local/bin/

      - name: Run tests
        run: pytest

      - name: Deploy to EC2
        if: success()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"  # Update with your region
        run: |
          # Install AWS CLI
          pip install awscli
          
          # Zip the project directory
          zip -r project.zip ./*
          
          # Upload the zip file to S3 (assumes you have a bucket named 'myapp-deployments')
          aws s3 cp project.zip s3://myapp-deployments/project.zip
          
          # Trigger deployment script on EC2 (assumes you have a script at /home/ubuntu/deploy.sh)
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_KEY_PAIR }} ubuntu@your-ec2-instance-public-dns 'bash -s' < deploy.sh
